/// <reference types="cypress"/>
it('Klika Webpage header buttons', function(){
    cy.visit('https://klika.us/')
    cy.get(':nth-child(1) > .nav-link').click()
    cy.visit('https://klika.us')
    cy.get(':nth-child(3) > .nav-link').click()
    cy.visit('https://klika.us')
    cy.get(':nth-child(4) > .nav-link').click()
    cy.visit('https://klika.us')
    cy.get(':nth-child(5) > .nav-link').click()
    cy.visit('https://klika.us')
    cy.get(':nth-child(6) > .nav-link').click()
    cy.visit('https://klika.us')
    cy.get(':nth-child(7) > .nav-link').click()
    cy.visit('https://klika.us')
    cy.get('#whatwedo-dropdown').click()
    cy.get('.dropdown-menu > [href="/whatwedo"]').click({force: true})
    cy.get('#whatwedo-dropdown').click()
    cy.get('[href="/agile"]').click({force: true})
    cy.get('#whatwedo-dropdown').click()
    cy.get('[href="/engineering"]').click({force: true})
    cy.get('#whatwedo-dropdown').click()
    cy.get('[href="/digital-transformation"]').click({force: true})
    cy.get('#whatwedo-dropdown').click()
    cy.get('[href="/advanced-technologies"]').click({force: true})
    cy.get('#whatwedo-dropdown').click()
    cy.get('[href="/penetration-testing"]').click({force: true})
    cy.get('.navbar-brand > img').click()

})